session_name: navi
windows:
  - window_name: navi-main
    layout: main-vertical
    shell_command_before:
      - cd ${SIM_DIR}/ros_ws
      - colcon build --symlink-install
      - source install/setup.bash
    panes:
      - shell_command:
        - echo "Welcome to Navi autonomy! Main terminal."
        -
      - shell_command:
          - echo "Opening control UI"