services:
  navi-sim:
    image: theairlab/navi-sim:x86
    container_name: navi-sim
    build:
      context: .
      dockerfile: navi-sim.Dockerfile
      args:
        BASE_IMAGE: theairlab/darpa-triage:x86-03-ros2
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host
    environment:
      - SIM_DIR=${SIM_DIR}
      - ROBOT_NAME=${ROBOT_NAME}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable
      - XAUTHORITY=/root/.Xauthority  # Ensure X11 uses the correct authority file
      - DEVICE_TYPE="x86"
      - CONDA_PREFIX=${CONDA_PREFIX}
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./.bashrc:/root/.bashrc:rw
      - ./.bash_history:/root/.bash_history:rw
      - /dev:/dev
      - /etc/udev:/etc/udev
      # Mounting the working directory to the container
      - ../ros_ws:${SIM_DIR}/ros_ws:rw
    stdin_open: true
    tty: true
    # Run the entrypoint shell script
    entrypoint: [ "/bin/bash", "${SIM_DIR}/entrypoint/navi-sim.sh" ]

