services:
  isaac-sim:
    profiles:
      - ""
      - sitl
      - hitl
    image: navi/isaac-sim:latest
    build:
      context: ../
      dockerfile: docker/navi-sim.Dockerfile
    container_name: navi-isaac-sim
    ipc: host
    privileged: true
    network_mode: host
    deploy:
      # let it use the GPU
      resources:
        reservations:
          devices:
            - driver: nvidia # https://stackoverflow.com/a/70761193
              count: 1
              capabilities: [gpu]
    environment:
      # NVIDIA stuff
      - ACCEPT_EULA=Y
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority  # Ensure X11 uses the correct authority file
      - DEVICE_TYPE="x86"
      # ROS2 stuff
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/isaac-sim/fastdds.xml
      - SIM_DIR=${SIM_DIR}
      - ROBOT_NAME=${ROBOT_NAME}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./.bashrc:/root/.bashrc:rw
      - ./.bash_history:/root/.bash_history:rw
      - /dev:/dev
      - /etc/udev:/etc/udev
      # Mounting the working directory to the container
      - ../ros_ws:${SIM_DIR}/ros_ws:rw
      - ./entrypoint:${SIM_DIR}/entrypoint:rw
      - ../assets:${SIM_DIR}/assets:rw
    stdin_open: true
    tty: true
    # Run the entrypoint shell script
    entrypoint: [ "/bin/bash", "${SIM_DIR}/entrypoint/navi-sim.sh" ]
  # ===================================================================================================================
