version: '3'

services:
  robot-spot:
    image: theairlab/robot-spot:x86
    container_name: robot-spot
    build:
      context: .
      dockerfile: robot-spot.Dockerfile
      args:
        BASE_IMAGE: theairlab/darpa-triage:x86-03-ros2
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host
    environment:
      - ROBOT_DIR=${ROBOT_DIR}
      - ROBOT_NAME=${ROBOT_NAME}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable
      - XAUTHORITY=/root/.Xauthority  # Ensure X11 uses the correct authority file
      - DEVICE_TYPE="x86"
      - CONDA_PREFIX=${CONDA_PREFIX}
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./.bashrc:/root/.bashrc:rw
      - ./.bash_history:/root/.bash_history:rw
      - /dev:/dev
      - /etc/udev:/etc/udev
      # Mounting the working directory to the container
      - ../ros_ws:${ROBOT_DIR}/ros_ws:rw
      - ./entrypoint:${ROBOT_DIR}/entrypoint:rw
    stdin_open: true
    tty: true
    # Run the entrypoint shell script
    entrypoint: [ "/bin/bash", "${ROBOT_DIR}/entrypoint/robot-spot.sh" ]



include:
  - path: ../simulation/docker/docker-compose-x86.yaml
    env_file: ../simulation/docker/.env