controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - front_right_leg_joint
      - front_right_thigh_joint
      - front_right_shin_joint
      - front_left_leg_joint
      - front_left_thigh_joint
      - front_left_shin_joint
      - rear_right_leg_joint
      - rear_right_thigh_joint
      - rear_right_shin_joint
      - rear_left_leg_joint
      - rear_left_thigh_joint
      - rear_left_shin_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


